# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

biz = Category.create!(name_en: 'business',
                       name_de: 'business',
                       image: '/categories/business-1012761_1920.png',
                       action_word_en: 'grow',
                       action_word_de: 'wachsen'
                      )
sci = Category.create!(name_en: 'tech & science',
                       name_de: 'technologie & wissenschaft',
                       image: '/categories/robot-507811_1920.png',
                       action_word_en: 'discover',
                       action_word_de: 'entdecken'
                      )
arts = Category.create!(name_en: 'arts & creative',
                        name_de: 'kunst & kreatives ',
                        image: '/categories/brush-1683134_1920.png',
                        action_word_en: 'create',
                        action_word_de: 'basteln'
                       )
life = Category.create!(name_en: 'lifestyle',
                        name_de: 'lifestyle',
                        image: '/categories/legs-434918_1280.png',
                        action_word_en: 'enjoy',
                        action_word_de: 'genießen'
                       )
Category.create!(name_en: 'kids',
                 name_de: 'kids',
                 image: '/categories/kids.png',
                 action_word_en: 'play',
                 action_word_de: 'spielen'
                )
Category.create!(name_en: 'tutor',
                 name_de: 'tutor',
                 image: '/categories/children-286239_1920.png',
                 action_word_en: 'nurture',
                 action_word_de: 'fördern'
                )

Level.create!([
  {value: 0, name_de: 'Neuling', name_en: 'Novice'},
  {value: 20, name_de: 'Anfänger', name_en: 'Beginner'},
  {value: 40, name_de: 'Fortgeschrittene Anfänger', name_en: 'Advanced Beginner'},
  {value: 60, name_de: 'Kompetant', name_en: 'Knowledgeable'},
  {value: 80, name_de: 'Expert', name_en: 'Expert'},
  {value: 100, name_de: 'Guru', name_en: 'Guru'}
])

User.create!([
  {email: Faker::Name.last_name + '@example.com', name: Faker::Name.last_name, first_name: Faker::Name.first_name, locale: "de", image: "/profile/200x200_boy_face.png", password: Faker::Internet.password(10, 20)},
  {email: Faker::Name.last_name + '@example.com', name: Faker::Name.last_name, first_name: Faker::Name.first_name, locale: "de", image: "/profile/200x200_grandma_hat.png", password: Faker::Internet.password(10, 20)},
  {email: Faker::Name.last_name + '@example.com', name: Faker::Name.last_name, first_name: Faker::Name.first_name, locale: "de", image: "/profile/200x200_lady_close_up.png", password: Faker::Internet.password(10, 20)},
  {email: Faker::Name.last_name + '@example.com', name: Faker::Name.last_name, first_name: Faker::Name.first_name, locale: "de", image: "/profile/200x200_old_man.png", password: Faker::Internet.password(10, 20)},
  {email: Faker::Name.last_name + '@example.com', name: Faker::Name.last_name, first_name: Faker::Name.first_name, locale: "de", image: "/profile/200x200_pyramid_hair_man.png", password: Faker::Internet.password(10, 20)},
  {email: Faker::Name.last_name + '@example.com', name: Faker::Name.last_name, first_name: Faker::Name.first_name, locale: "de", image: "/profile/200x200_shy_lady.png", password: Faker::Internet.password(10, 20)},
  {email: Faker::Name.last_name + '@example.com', name: Faker::Name.last_name, first_name: Faker::Name.first_name, locale: "de", image: "/profile/200x200_soph_lady.png", password: Faker::Internet.password(10, 20)}
])

Workshop.create!(title_en: 'Communication and HR',
  title_de: 'Kommunikation',
  subtitle_en: 'Effective Communication and Human Relations',
  subtitle_de: 'Besser kommunizieren',
  description_en: 'This workshop helps you strengthen your communication skills. You will learn how to be more confident when talking about your business, how to be inspiring and entertaining while explaining something and how to empower others to succeed. ',
  description_de: 'Praesent convallis, turpis feugiat malesuada pellentesque, ante tellus hendrerit mi, quis viverra neque ipsum sed nisi. Suspendisse id ullamcorper nisl, ac interdum ex. Morbi odio elit, sollicitudin at tellus vitae, ornare feugiat ex. Ut consectetur auctor lectus, id vehicula diam auctor id',
  category: biz,
  action_word: 'communicate',
  provider: User.all.sample,
  main_image: '/workshops/workplace.png')
Workshop.create!(title_en: 'Digital Marketing',
  title_de: 'Digital Marketing',
  subtitle_en: 'Marketing with heart',
  subtitle_de: 'Marketing mit Herz',
  description_en: 'Acquire the right skills to drive your revenue, know your customers and work with technology.',
  description_de: 'Acquire die richtigen Faehigkeiten, um Ihre Einnahmen zu erhöhen und kennen Ihre Kunden',
  category: biz,
  action_word: 'marketing',
  provider: User.all.sample,
  main_image: '/workshops/business.png')
Workshop.create!(title_en: 'Entrepreneurship ',
  title_de: 'Entrepreneurship ',
  subtitle_en: 'Make Ideas Happen',
  subtitle_de: 'Führerschaft und soziale Kompetenz',
  description_en: 'Brining an idea to success is a long and tiresome journey. But the reward for reaching the end of the journey can be utterly rewarding. This workshop gives entrepreneurs an understanding of the process, risqué, challenges and rewards of starting a startup. It helps develop a business plan, teaches the necessary skills of how to work with a team, and gives tips on how to raise funding. ',
  description_de: 'Problemlösung, Entscheidungsfindung, Planung und Delegation',
  category: biz,
  action_word: 'entrepreneur ',
  provider: User.all.sample,
  main_image: '/workshops/work-management.png')
Workshop.create!(title_en: 'Business Planning',
  title_de: 'Business Planung',
  subtitle_en: 'Your Business, your Plan!',
  subtitle_de: 'Dein Geschäft, dein Plan!',
  description_en: 'Praesent viverra erat nec leo feugiat lacinia. Quisque eget eros vehicula, pharetra eros sit amet, aliquet purus. Ut ut sodales felis. Mauris tempor sit amet urna ac dignissim. Morbi efficitur ultricies velit, eget tristique urna condimentum et. Donec commodo aliquam nisl, eget dignissim dui pulvinar eu',
  description_de: 'This workshop helps you develop your business idea into a complete and detailed business plan. It also gives personalised tips and guiding on how to start and grow your business. ',
  category: biz,
  action_word: 'business planning ',
  provider: User.all.sample,
  main_image: '/workshops/hand.png')
Workshop.create!(title_en: 'Strategic Management',
  title_de: 'Strategisches Management',
  subtitle_en: 'Plan Business Strategies',
  subtitle_de: 'Plane neue Strategien',
  description_en: 'Strategic Management is of vital importance of business growth and development. Learn how to create, plan and execute business strategies for your startup or company. ',
  description_de: ' Curabitur tempus augue sit amet augue rutrum, at aliquam felis dictum. Phasellus diam ligula, molestie sed elit et, malesuada maximus urna.',
  category: biz,
  action_word: 'strategise ',
  provider: User.all.sample,
  main_image: '/workshops/the-strategy.png')
Workshop.create!(title_en: 'WebDesign ',
  title_de: 'WebDesign',
  subtitle_en: 'Design your website to look awesome',
  subtitle_de: 'Entwicklen Sie Ihre eigenen App',
  description_en: 'This workshop teaches you the foundation of WebDesign. You will learn about alignment, color, typography, hierarchy, and how to apply those principles onto your own project.',
  description_de: 'Fähigkeiten, um eine App zu entwickeln ',
  category: sci,
  action_word: 'WebDesign',
  provider: User.all.sample,
  main_image: '/workshops/tablet.png')
Workshop.create!(title_en: 'Adobe Photoshop',
  title_de: 'Adobe Photoshop',
  subtitle_en: 'Master the craft of Adobe Photoshop',
  subtitle_de: 'Lernen die wichtigsten Adobe Grundlagen',
  description_en: 'Nam vulputate pellentesque leo vel sagittis. Pellentesque porta vel ipsum ac consectetur. Nullam in varius ante. Vivamus lacinia quis magna',
  description_de: 'Do you already know the basics of Photoshop? Do you wish to improve your skills and create some amazing work? This workshop helps rising Photoshop masters to enhance their abilities and be able to more professionally work with the software. ',
  category: sci,
  action_word: 'photoshop',
  provider: User.all.sample,
  main_image: '/workshops/adobe.png')
Workshop.create!(title_en: 'Daily Chemistry',
  title_de: 'Alltags Chemie',
  subtitle_en: 'Chemical creations for daily usage',
  subtitle_de: 'Chemische tipps für den Alltag',
  description_en: 'Do you know how bad cleaning products can be for your health? Are you aware how much you spend only on cleaning products? What if we told you that you can create your own cleaning products that will cost less and will be much better for your health? It does not matter if you believe us or not, just join this workshop and we will change the way you do the most basic everyday activities. ',
  description_de: 'Praesent sit amet ante nec massa ultricies bibendum. Integer tincidunt purus ac nunc porta lobortis. Nunc laoreet scelerisque bibendum.',
  category: sci,
  action_word: 'chemistry ',
  provider: User.all.sample,
  main_image: '/workshops/chemistry.png')
Workshop.create!(title_en: 'Winterproof your car',
  title_de: 'Mach dein Auto Winterfit',
  subtitle_en: 'Easy tricks for hobby mechanics',
  subtitle_de: 'Einfache tricks für Hobbybastler',
  description_en: 'Mauris vel eros et metus feugiat sollicitudin non at dolor. Integer eu porta ipsum, id condimentum metus. Maecenas consectetur mattis risus, eu elementum nulla porta tempus. Etiam id rhoncus neque. Nunc eget metus eu augue efficitur mollis',
  description_de: 'Learn how to deal with basics of auto mechanics. After this workshop you will know how to get your car ready for the cold winter days.  ',
  category: sci,
  action_word: 'auto mechanics ',
  provider: User.all.sample,
  main_image: '/workshops/car.png')
Workshop.create!(title_en: 'Pottery',
  title_de: 'Töpfern',
  subtitle_en: 'Learn the art of pottery',
  subtitle_de: 'Lerne die Kunst des Töpferns',
  description_en: 'This workshop gives you the perfect chance to improve your pottery skills. Create a new ornament for your home, or a present for a loved one, or just enjoy a creative time. The workshop is suitable for all levels, no prior knowledge is required, but if you have already some skills we will help you master the craft. ',
  description_de: 'Praesent sit amet ante nec massa ultricies bibendum. Integer tincidunt purus ac nunc porta lobortis. Nunc laoreet scelerisque bibendum.',
  category: arts,
  action_word: 'potter',
  provider: User.all.sample,
  main_image: '/workshops/clay.png')
Workshop.create!(title_en: 'Knit Hats and Scarfs',
  title_de: 'Mützen und Schals Stricken',
  subtitle_en: 'Winter is coming ',
  subtitle_de: 'Der Winter kommt',
  description_en: 'Nunc ultrices tempus tortor, a cursus ex dapibus vitae. Nulla congue libero id ipsum pharetra, id scelerisque dui commodo. Aenean sit amet nisl gravida, ullamcorper massa a',
  description_de: 'Days are getting colder, and we want you to stay warm and cosy, but most of all we want you to stay unique and trendy. This workshop gives you the opportunity to put your creativity into action by learning how to knit your own winter hat and scarf. You can make it look anyway you want to, and after you walk out of this workshop everyone will admire you. So what is it going to be, a pink fluffy hat, or a green one with ears? ',
  category: arts,
  action_word: 'knit',
  provider: User.all.sample,
  main_image: '/workshops/wool.png')
Workshop.create!(title_en: 'Creative Writing',
  title_de: 'Kreatives Schreiben',
  subtitle_en: 'Release your Imagination ',
  subtitle_de: 'Erschaffe deine Charaktere',
  description_en: 'We know that you are amazingly creative and have a wonderful imagination. That is why you should join this workshop and embark with us on a creative writing adventure. You will not only improve your writing skills, but you will also finish your own story that people cannot wait to read. ',
  description_de: 'Praesent sit amet ante nec massa ultricies bibendum. Integer tincidunt purus ac nunc porta lobortis. Nunc laoreet scelerisque bibendum.',
  category: arts,
  action_word: 'story',
  provider: User.all.sample,
  main_image: '/workshops/home-office.png')
Workshop.create!(title_en: 'Balcony Gardening ',
  title_de: 'Grundlagen für Hobbygärtner',
  subtitle_en: 'Gardening',
  subtitle_de: 'Gardening',
  description_en: 'You love the city, but you miss having a garden? Unfortunately we cannot supply you with a new yard but we can help you transform your balcony into an amazing green paradise. After this workshop you will have all the necessary skills to plant and maintain your beautiful balcony flowers, herbs, fruits and vegetables.   ',
  description_de: 'Praesent sit amet ante nec massa ultricies bibendum. Integer tincidunt purus ac nunc porta lobortis. Nunc laoreet scelerisque bibendum.',
  category: life,
  action_word: 'gardening ',
  provider: User.all.sample,
  main_image: '/workshops/dahlia.png')
Workshop.create!(title_en: 'Programming for Beginners',
  title_de: 'Programmieren für Anfänger',
  subtitle_en: 'Create your first App',
  subtitle_de: 'Erstelle deine erste App',
  description_en: 'The only skill you need for this workshop is your creativeness. Think about the app you want to create and we will help you bring it to life.   ',
  description_de: 'Praesent sit amet ante nec massa ultricies bibendum. Integer tincidunt purus ac nunc porta lobortis. Nunc laoreet scelerisque bibendum.',
  category: sci,
  action_word: 'code',
  provider: User.all.sample,
  main_image: '/workshops/laptop.png')
Workshop.create!(title_en: 'Mathematics for Beginners',
  title_de: 'Mathematik für Einsteiger',
  subtitle_en: 'Numbers made easy',
  subtitle_de: 'Zahlen einfach gemacht',
  description_en: 'Numbers, Numbers, Numbers... Make them your friends.',
  description_de: 'Praesent sit amet ante nec massa ultricies bibendum. Integer tincidunt purus ac nunc porta lobortis. Nunc laoreet scelerisque bibendum.',
  category: sci,
  action_word: 'calculate',
  provider: User.all.sample,
  main_image: '/workshops/math.png')
Workshop.create!(title_en: 'Music',
  title_de: 'Musik',
  subtitle_en: 'Learn to play the cello  ',
  subtitle_de: 'Lerne ein Instrument',
  description_en: 'Cello is a powerful instrument, it can be gentle, utterly emotional or even cheerful. Join this workshop and learn to express your feelings through this amazing instrument. ',
  description_de: 'Praesent sit amet ante nec massa ultricies bibendum. Integer tincidunt purus ac nunc porta lobortis. Nunc laoreet scelerisque bibendum.',
  category: arts,
  action_word: 'cello',
  provider: User.all.sample,
  main_image: '/workshops/country.png')
Workshop.create!(title_en: 'Design your own Fashion',
  title_de: 'Design deine eigene Mode',
  subtitle_en: 'Upcycling Attire ',
  subtitle_de: 'Dein mode',
  description_en: 'Do you have a closet full of old clothes that have left the fashionable trend? Instead of getting rid of them why not transform them into something new? Bring your old clothes to this workshop, and together we will convert them into your new favourite outfits. ',
  description_de: 'Praesent sit amet ante nec massa ultricies bibendum. Integer tincidunt purus ac nunc porta lobortis. Nunc laoreet scelerisque bibendum.',
  category: life,
  action_word: 'style ',
  provider: User.all.sample,
  main_image: '/workshops/fashion.png')
Workshop.create!(title_en: 'Run Training',
  title_de: 'Lauftraining',
  subtitle_en: 'Become a stronger and faster runner ',
  subtitle_de: 'Werde ein stärkerer und schnellerer Läufer ',
  description_en: 'Do you want to improve your running time? Do you want to feel stronger and more powerful while running? This workshop will help you improve your running skills and technique. In just three days you will feel a difference and will be able to focus on your next running challenge. Who knows maybe you will continue to become the next marathon winner. ',
  description_de: 'Praesent sit amet ante nec massa ultricies bibendum. Integer tincidunt purus ac nunc porta lobortis. Nunc laoreet scelerisque bibendum.',
  category: life,
  action_word: 'workout',
  provider: User.all.sample,
  main_image: '/workshops/yoga.png')
Workshop.create!(title_en: 'After Effects',
  title_de: 'After Effects',
  subtitle_en: 'Create amazing video effects',
  subtitle_de: 'Create amazing video effects',
  description_en: 'Are you a film or video enthusiast? Then broaden your skills and learn how to make your films and videos look awesome with after effects. ',
  description_de: 'Praesent sit amet ante nec massa ultricies bibendum. Integer tincidunt purus ac nunc porta lobortis. Nunc laoreet scelerisque bibendum.',
  category: sci,
  action_word: 'after effects',
  provider: User.all.sample,
  main_image: '/workshops/monitor.png')
