# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

biz = Category.create!(name_en: 'Business',
                       name_de: 'Das Unternehmen',
                       image: '/assets/categories/business-1012761_1920.png',
                       action_word_en: 'grow',
                       action_word_de: 'wachsen'
                      )
sci = Category.create!(name_en: 'Tech & Science',
                       name_de: 'Technologie & Wissenschaft',
                       image: '/assets/categories/robot-507811_1920.png',
                       action_word_en: 'discover',
                       action_word_de: 'entdecken'
                      )
arts = Category.create!(name_en: 'Creative & Arts',
                        name_de: 'Kreative und Kunst.',
                        image: '/assets/categories/brush-1683134_1920.png',
                        action_word_en: 'create',
                        action_word_de: 'basteln'
                       )
life = Category.create!(name_en: 'Lifestyle',
                        name_de: 'Lebensstil.',
                        image: '/assets/categories/legs-434918_1280.png',
                        action_word_en: 'enjoy',
                        action_word_de: 'genießen'
                       )
Category.create!(name_en: 'Kids',
                 name_de: 'Kinder',
                 image: '/assets/categories/kids.png',
                 action_word_en: 'play',
                 action_word_de: 'spielen'
                )
Category.create!(name_en: 'Tutoring',
                 name_de: 'Unterrichten',
                 image: '/assets/categories/children-286239_1920.png',
                 action_word_en: 'nurture',
                 action_word_de: 'fördern'
                )

Level.create!([
  {value: 0, name_de: 'Neuling', name_en: 'Novice'},
  {value: 20, name_de: 'Anfänger', name_en: 'Beginner'},
  {value: 40, name_de: 'Fortgeschrittene Anfänger', name_en: 'Advanced Beginner'},
  {value: 60, name_de: 'Kompetant', name_en: 'Knowledgeable'},
  {value: 80, name_de: 'Expert', name_en: 'Expert'},
  {value: 100, name_de: 'Guru', name_en: 'Guru'}
])

User.create!([
  {email: Faker::Name.last_name + '@example.com', name: Faker::Name.last_name, first_name: Faker::Name.first_name, locale: "de", image: "/assets/profile/200x200_boy_face.png", password: Faker::Internet.password(10, 20)},
  {email: Faker::Name.last_name + '@example.com', name: Faker::Name.last_name, first_name: Faker::Name.first_name, locale: "de", image: "/assets/profile/200x200_grandma_hat.png", password: Faker::Internet.password(10, 20)},
  {email: Faker::Name.last_name + '@example.com', name: Faker::Name.last_name, first_name: Faker::Name.first_name, locale: "de", image: "/assets/profile/200x200_lady_close_up.png", password: Faker::Internet.password(10, 20)},
  {email: Faker::Name.last_name + '@example.com', name: Faker::Name.last_name, first_name: Faker::Name.first_name, locale: "de", image: "/assets/profile/200x200_old_man.png", password: Faker::Internet.password(10, 20)},
  {email: Faker::Name.last_name + '@example.com', name: Faker::Name.last_name, first_name: Faker::Name.first_name, locale: "de", image: "/assets/profile/200x200_pyramid_hair_man.png", password: Faker::Internet.password(10, 20)},
  {email: Faker::Name.last_name + '@example.com', name: Faker::Name.last_name, first_name: Faker::Name.first_name, locale: "de", image: "/assets/profile/200x200_shy_lady.png", password: Faker::Internet.password(10, 20)},
  {email: Faker::Name.last_name + '@example.com', name: Faker::Name.last_name, first_name: Faker::Name.first_name, locale: "de", image: "/assets/profile/200x200_soph_lady.png", password: Faker::Internet.password(10, 20)}
])

Workshop.create!(title_en: 'Communication',
                 title_de: 'Kommunikation',
                 subtitle_en: 'Get communicative',
                 subtitle_de: 'Besser kommunizieren',
                 description_en: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed iaculis velit. Mauris finibus nunc vitae dui aliquet aliquet. Suspendisse convallis mi id elit pharetra, id fringilla nunc laoreet. Morbi condimentum, mi ac ullamcorper bibendum, lacus sem cursus sem, eu facilisis nulla elit vel mi. Phasellus ut diam pretium, consequat lacus eget, mattis dolor. Nunc blandit, dui eu tempor scelerisque, ante purus consectetur est, sed sagittis erat nunc quis quam',
                 description_de: 'Praesent convallis, turpis feugiat malesuada pellentesque, ante tellus hendrerit mi, quis viverra neque ipsum sed nisi. Suspendisse id ullamcorper nisl, ac interdum ex. Morbi odio elit, sollicitudin at tellus vitae, ornare feugiat ex. Ut consectetur auctor lectus, id vehicula diam auctor id',
                 category: biz,
                 action_word: 'communicate',
                 provider: User.all.sample,
                 main_image: '/assets/workshops/workplace.png')
Workshop.create!(title_en: 'Marketing',
                 title_de: 'Marketing',
                 subtitle_en: 'Learn to feel the pulse of the market',
                 subtitle_de: 'Lernen Sie den Pul des Markets zu spueren',
                 description_en: 'Acquire the right skills to drive your revenue, know your customers and work with technology.',
                 description_de: 'Acquire die richtigen Faehigkeiten, um Ihre Einnahmen zu erhöhen und kennen Ihre Kunden',
                 category: biz,
                 action_word: 'market',
                 provider: User.all.sample,
                 main_image: '/assets/workshops/business.png')
Workshop.create!(title_en: 'Management',
                 title_de: 'Management',
                 subtitle_en: 'Leadership and interpersonal skills',
                 subtitle_de: 'Führerschaft und soziale Kompetenz',
                 description_en: 'Problem solving, decision making, planning and delegation',
                 description_de: 'Problemlösung, Entscheidungsfindung, Planung und Delegation',
                 category: biz,
                 action_word: 'manage',
                 provider: User.all.sample,
                 main_image: '/assets/workshops/work-management.png')
Workshop.create!(title_en: 'Business Planning',
                 title_de: 'Business Planning',
                 subtitle_en: 'Get your business in order',
                 subtitle_de: 'Dein Geschäft, dein Plan',
                 description_en: 'Praesent viverra erat nec leo feugiat lacinia. Quisque eget eros vehicula, pharetra eros sit amet, aliquet purus. Ut ut sodales felis. Mauris tempor sit amet urna ac dignissim. Morbi efficitur ultricies velit, eget tristique urna condimentum et. Donec commodo aliquam nisl, eget dignissim dui pulvinar eu',
                 description_de: 'Nunc non enim non neque consequat dignissim et vitae tellus. Curabitur non molestie urna. Donec suscipit purus condimentum, euismod ex quis, facilisis dui. Suspendisse nec turpis et enim pulvinar pellentesque. Pellentesque et ligula vitae tortor viverra vehicula. Suspendisse luctus vitae mi eget tristique',
                 category: biz,
                 action_word: 'plan ahead',
                 provider: User.all.sample,
                 main_image: '/assets/workshops/hand.png')
Workshop.create!(title_en: 'Strategic Planning',
                 title_de: 'Strategic Planning',
                 subtitle_en: 'Plan your strategies',
                 subtitle_de: 'Plan your strategies',
                 description_en: 'In fringilla urna nulla, in vestibulum neque maximus vitae. Donec varius mi sed dui accumsan placerat. Donec sit amet diam orci. Curabitur at felis egestas, tincidunt velit in, posuere odio. Integer ut diam massa. Cras consectetur sem pellentesque mi egestas lobortis. Curabitur mollis justo purus, ut consequat odio volutpat id',
                 description_de: ' Curabitur tempus augue sit amet augue rutrum, at aliquam felis dictum. Phasellus diam ligula, molestie sed elit et, malesuada maximus urna.',
                 category: biz,
                 action_word: 'strategize',
                 provider: User.all.sample,
                 main_image: '/assets/workshops/the-strategy.png')
Workshop.create!(title_en: 'App Development',
                 title_de: 'App Development',
                 subtitle_en: 'Build your own Apps',
                 subtitle_de: 'Entwicklen Sie Ihre eigenen App',
                 description_en: 'Skills to develop your own idea into an Application',
                 description_de: 'Fähigkeiten, um eine App zu entwickeln ',
                 category: sci,
                 action_word: 'ideate',
                 provider: User.all.sample,
                 main_image: '/assets/workshops/tablet.png')
Workshop.create!(title_en: 'Adobe Workshops',
                 title_de: 'Adobe Workshops',
                 subtitle_en: 'Know the Adobe products',
                 subtitle_de: 'Lernen die Adobeprodukten kennen',
                 description_en: 'Nam vulputate pellentesque leo vel sagittis. Pellentesque porta vel ipsum ac consectetur. Nullam in varius ante. Vivamus lacinia quis magna',
                 description_de: 'Quisque dolor lorem, efficitur in ex sed, laoreet aliquam ante. Vestibulum feugiat lacinia mi in venenatis. Praesent vitae lectus urna. Aenean rutrum fermentum lectus, in scelerisque justo posuere et. Suspendisse augue elit, commodo nec erat eu, facilisis eleifend sem. Sed euismod et ligula id vehicula',
                 category: sci,
                 action_word: 'photoshop',
                 provider: User.all.sample,
                 main_image: '/assets/workshops/adobe.png')
Workshop.create!(title_en: 'Chemistry',
                 title_de: 'Chemistry',
                 subtitle_en: 'Bond, covalent bond!',
                 subtitle_de: 'Chemistry',
                 description_en: 'Learn chemistry in a fun and easy way',
                 description_de: 'Praesent sit amet ante nec massa ultricies bibendum. Integer tincidunt purus ac nunc porta lobortis. Nunc laoreet scelerisque bibendum.',
                 category: sci,
                 action_word: 'react',
                 provider: User.all.sample,
                 main_image: '/assets/workshops/chemistry.png')
Workshop.create!(title_en: 'Auto Mechanics',
                 title_de: 'Auto Mechanics',
                 subtitle_en: 'Move those gears',
                 subtitle_de: 'Auto Mechanics',
                 description_en: 'Mauris vel eros et metus feugiat sollicitudin non at dolor. Integer eu porta ipsum, id condimentum metus. Maecenas consectetur mattis risus, eu elementum nulla porta tempus. Etiam id rhoncus neque. Nunc eget metus eu augue efficitur mollis',
                 description_de: 'Praesent sit amet ante nec massa ultricies bibendum. Integer tincidunt purus ac nunc porta lobortis. Nunc laoreet scelerisque bibendum.',
                 category: sci,
                 action_word: 'Auto Mechanics',
                 provider: User.all.sample,
                 main_image: '/assets/workshops/car.png')
Workshop.create!(title_en: 'Sculpting',
                 title_de: 'Sculpting',
                 subtitle_en: 'Art of sculpture making',
                 subtitle_de: 'Sculpting',
                 description_en: 'Mauris vel eros et metus feugiat sollicitudin non at dolor. Integer eu porta ipsum, id condimentum metus. Maecenas consectetur mattis risus, eu elementum nulla porta tempus. Etiam id rhoncus neque. Nunc eget metus eu augue efficitur mollis',
                 description_de: 'Praesent sit amet ante nec massa ultricies bibendum. Integer tincidunt purus ac nunc porta lobortis. Nunc laoreet scelerisque bibendum.',
                 category: arts,
                 action_word: 'sculpt',
                 provider: User.all.sample,
                 main_image: '/assets/workshops/clay.png')
Workshop.create!(title_en: 'Knitting',
                 title_de: 'Stricken',
                 subtitle_en: 'Needles and threads',
                 subtitle_de: 'Der Winter kommt',
                 description_en: 'Nunc ultrices tempus tortor, a cursus ex dapibus vitae. Nulla congue libero id ipsum pharetra, id scelerisque dui commodo. Aenean sit amet nisl gravida, ullamcorper massa a',
                 description_de: 'Ut mattis pellentesque ex eu rutrum. Pellentesque sollicitudin non dolor nec malesuada. In ac metus ultricies, fringilla dui et, sagittis tortor. Quisque consequat semper metus in rhoncus.',
                 category: arts,
                 action_word: 'knit',
                 provider: User.all.sample,
                 main_image: '/assets/workshops/wool.png')
Workshop.create!(title_en: 'Creative Writing',
                 title_de: 'Creative Writing',
                 subtitle_en: 'Creative Writing',
                 subtitle_de: 'Creative Writing',
                 description_en: 'Mauris vel eros et metus feugiat sollicitudin non at dolor. Integer eu porta ipsum, id condimentum metus. Maecenas consectetur mattis risus, eu elementum nulla porta tempus. Etiam id rhoncus neque. Nunc eget metus eu augue efficitur mollis',
                 description_de: 'Praesent sit amet ante nec massa ultricies bibendum. Integer tincidunt purus ac nunc porta lobortis. Nunc laoreet scelerisque bibendum.',
                 category: arts,
                 action_word: 'write',
                 provider: User.all.sample,
                 main_image: '/assets/workshops/home-office.png')
Workshop.create!(title_en: 'Gardening',
                 title_de: 'Gardening',
                 subtitle_en: 'Gardening',
                 subtitle_de: 'Gardening',
                 description_en: 'Mauris vel eros et metus feugiat sollicitudin non at dolor. Integer eu porta ipsum, id condimentum metus. Maecenas consectetur mattis risus, eu elementum nulla porta tempus. Etiam id rhoncus neque. Nunc eget metus eu augue efficitur mollis',
                 description_de: 'Praesent sit amet ante nec massa ultricies bibendum. Integer tincidunt purus ac nunc porta lobortis. Nunc laoreet scelerisque bibendum.',
                 category: life,
                 action_word: 'garden',
                 provider: User.all.sample,
                 main_image: '/assets/workshops/dahlia.png')
Workshop.create!(title_en: 'Coding',
                 title_de: 'Coding',
                 subtitle_en: 'Coding for beginners',
                 subtitle_de: 'Coding für Anfänger',
                 description_en: 'Mauris vel eros et metus feugiat sollicitudin non at dolor. Integer eu porta ipsum, id condimentum metus. Maecenas consectetur mattis risus, eu elementum nulla porta tempus. Etiam id rhoncus neque. Nunc eget metus eu augue efficitur mollis',
                 description_de: 'Praesent sit amet ante nec massa ultricies bibendum. Integer tincidunt purus ac nunc porta lobortis. Nunc laoreet scelerisque bibendum.',
                 category: sci,
                 action_word: 'code',
                 provider: User.all.sample,
                 main_image: '/assets/workshops/laptop.png')
Workshop.create!(title_en: 'Mathematics',
                 title_de: 'Mathematics',
                 subtitle_en: 'Numbers made easy',
                 subtitle_de: 'Mathematik für alle',
                 description_en: 'Numbers, Numbers, Numbers... Make them your friends',
                 description_de: 'Praesent sit amet ante nec massa ultricies bibendum. Integer tincidunt purus ac nunc porta lobortis. Nunc laoreet scelerisque bibendum.',
                 category: sci,
                 action_word: 'compute',
                 provider: User.all.sample,
                 main_image: '/assets/workshops/math.png')
Workshop.create!(title_en: 'Music',
                 title_de: 'Music',
                 subtitle_en: 'Learn Music',
                 subtitle_de: 'Musik machen',
                 description_en: 'Mauris vel eros et metus feugiat sollicitudin non at dolor. Integer eu porta ipsum, id condimentum metus. Maecenas consectetur mattis risus, eu elementum nulla porta tempus. Etiam id rhoncus neque. Nunc eget metus eu augue efficitur mollis',
                 description_de: 'Praesent sit amet ante nec massa ultricies bibendum. Integer tincidunt purus ac nunc porta lobortis. Nunc laoreet scelerisque bibendum.',
                 category: arts,
                 action_word: 'music',
                 provider: User.all.sample,
                 main_image: '/assets/workshops/country.png')
Workshop.create!(title_en: 'Fashion',
                 title_de: 'Fashion',
                 subtitle_en: 'Your Fashion',
                 subtitle_de: 'Dein Fashion',
                 description_en: 'Mauris vel eros et metus feugiat sollicitudin non at dolor. Integer eu porta ipsum, id condimentum metus. Maecenas consectetur mattis risus, eu elementum nulla porta tempus. Etiam id rhoncus neque. Nunc eget metus eu augue efficitur mollis',
                 description_de: 'Praesent sit amet ante nec massa ultricies bibendum. Integer tincidunt purus ac nunc porta lobortis. Nunc laoreet scelerisque bibendum.',
                 category: life,
                 action_word: 'fashion',
                 provider: User.all.sample,
                 main_image: '/assets/workshops/fashion.png')
Workshop.create!(title_en: 'Fitness',
                 title_de: 'Fitness',
                 subtitle_en: 'Fitness and Health',
                 subtitle_de: 'Fitness und Gesundheit',
                 description_en: 'Mauris vel eros et metus feugiat sollicitudin non at dolor. Integer eu porta ipsum, id condimentum metus. Maecenas consectetur mattis risus, eu elementum nulla porta tempus. Etiam id rhoncus neque. Nunc eget metus eu augue efficitur mollis',
                 description_de: 'Praesent sit amet ante nec massa ultricies bibendum. Integer tincidunt purus ac nunc porta lobortis. Nunc laoreet scelerisque bibendum.',
                 category: life,
                 action_word: 'workout',
                 provider: User.all.sample,
                 main_image: '/assets/workshops/yoga.png')
Workshop.create!(title_en: 'Programming',
                 title_de: 'Programmierung',
                 subtitle_en: 'Code your way',
                 subtitle_de: 'Deine Ideen umsetzen',
                 description_en: 'Mauris vel eros et metus feugiat sollicitudin non at dolor. Integer eu porta ipsum, id condimentum metus. Maecenas consectetur mattis risus, eu elementum nulla porta tempus. Etiam id rhoncus neque. Nunc eget metus eu augue efficitur mollis',
                 description_de: 'Praesent sit amet ante nec massa ultricies bibendum. Integer tincidunt purus ac nunc porta lobortis. Nunc laoreet scelerisque bibendum.',
                 category: sci,
                 action_word: 'program',
                 provider: User.all.sample,
                 main_image: '/assets/workshops/monitor.png')
